### ISSUE TITLE
Unrecognized option or missing or extra parameter(s) in [CMD-LINE]:1: config (2.4.0)

### ISSUE THREAD

**Issue by wkruse** [rodrigogs/easyvpn#9] opened 2017-02-10 19:01 UTC
Getting `Unrecognized option or missing or extra parameter(s) in [CMD-LINE]:1: config (2.4.0)` on macOS Sierra. Also there is something strange with the version. `npm` reports `1.2.0`. `easyvpn` reports `1.1.3`.

```
node --version
v7.5.0
```

```
openvpn --version
OpenVPN 2.4.0 x86_64-apple-darwin16.3.0 [SSL (OpenSSL)] [LZO] [LZ4] [MH/RECVDA] [AEAD] built on Dec 28 2016
library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.09
Originally developed by James Yonan
Copyright (C) 2002-2017 OpenVPN Technologies, Inc. <sales@openvpn.net>
Compile time defines: enable_async_push=no enable_comp_stub=no enable_crypto=yes enable_crypto_ofb_cfb=yes enable_debug=no enable_def_auth=yes enable_dependency_tracking=no enable_dlopen=unknown enable_dlopen_self=unknown enable_dlopen_self_static=unknown enable_fast_install=needless enable_fragment=yes enable_iproute2=no enable_libtool_lock=yes enable_lz4=yes enable_lzo=yes enable_management=yes enable_multi=yes enable_multihome=yes enable_pam_dlopen=no enable_password_save=yes enable_pedantic=no enable_pf=yes enable_pkcs11=no enable_plugin_auth_pam=yes enable_plugin_down_root=yes enable_plugins=yes enable_port_share=yes enable_selinux=no enable_server=yes enable_shared=yes enable_shared_with_static_runtimes=no enable_silent_rules=no enable_small=no enable_static=yes enable_strict=no enable_strict_options=no enable_systemd=no enable_werror=no enable_win32_dll=yes enable_x509_alt_username=no with_crypto_library=openssl with_gnu_ld=no with_mem_check=no with_plugindir='$(libdir)/openvpn/plugins' with_sysroot=no
```

```
easyvpn --version
1.1.3
```

```
npm list easyvpn -g
/usr/local/lib
└── easyvpn@1.2.0
```

```
easyvpn
info: Querying data...
info: Starting openvpn...
info: Options error: Unrecognized option or missing or extra parameter(s) in [CMD-LINE]:1: config (2.4.0)
info: Use --help for more information.
info:
info: child process exited with code 1
```

**Comment by rodrigogs** [comment] 2017-02-10 20:51
The version problem is very simple, I forgot to change it in commander(got to change it to get version from package.json) but I don't know why you're getting the openvpn error. I'll try to solve it later when I have some time.

**Comment by rodrigogs** [comment] 2017-02-11 17:57
Fixed the version problem, but I cant reproduce the unrecognized option error... I don't have a Mac.

**Comment by mukeshtiwari1987** [comment] 2017-03-10 10:57
I am on Mac and my set up is similar to @wkruse, even I am facing same error.

**Comment by rodrigogs** [comment] 2017-03-10 20:07
As I said, I dont have a Mac to test it.

Right now I'm travelling and I can't verify it, but maybe tomorrow I'll try give a look.

**Comment by rodrigogs** [comment] 2017-06-24 23:36
The last release may have fixed this problem.

**Comment by rodrigogs** [comment] 2017-12-20 02:29
Fixed with https://github.com/rodrigogs/easyvpn/commit/02260bb84f3233401e0b7cb0fb09cecde647c5cf

**Closed as completed by rodrigogs** 2017-12-20 02:29 UTC
Labels: bug
